[versions]
# Library and plugin versions
kotlin = "2.4.10"
androidGradlePlugin = "9.3.2"
composeMultiplatform = "1.12.0"
activity = "1.13.0"
splashScreen = "1.2.0"

# android module's configuration information
android-group = "dev.dayseven.app"
android-version = "1.0.0"

# android module's android app package information
android-compileSdk = "37"
android-minSdk = "24"
android-targetSdk = "37"
android-versionCode = "1"
android-versionName = "26.0.0"

# desktop module's configuration information
desktop-group = "dev.dayseven.app"
desktop-version = "1.0.0"
desktop-mainClass = "dev.dayseven.app.AppKt"
desktop-packageOfResClass = "dev.dayseven.app.desktop.resources"

# desktop module's distribution information
desktop-distributionPackageName = "DaySeven"
desktop-distributionPackageVersion = "26.0.0"

# design-system module's configuration information
compose-group = "dev.dayseven.app.compose"
compose-version = "1.0.0"

# design-system module's configuration information
designSystem-group = "dev.dayseven.app.design.system"
designSystem-version = "1.0.0"

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
compose-multiplatform-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }

[bundles]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }